#Alan De Lara, Expressions Practice - C



var_one = 7-24/8*4+6;
var_two = 18/3-7+2*5;
var_three = 6*4/12+72/8-9;
var_four = (17 - 6 / 2) + 4 * 3;
var_five = -2*(1*4-2/2)+(6+2-3);
var_six = -1 * ((3 - 4 * 7) / 5) - 2 * 24 / 6;
var_seven = (3*pow(5,2) / 15) - (5 - pow(2,2));
var_eight = (pow(1,4)*pow(2,2) + pow(3,3)) - pow(2,5) / 4;
var_nine = pow((22 / 2 - 2 * 5),2) + pow((4 - 6 / 6),2);
 
print(var_one, var_two, var_three, var_four, var_five, var_six, var_seven, var_eight, var_nine);  
 
